In [1]:
import numpy as np

np_marks=np.array([10,20,30])
print(np_marks)


[10 20 30]


In [3]:
print(np_marks.shape)
print(np_marks.dtype)
print(np_marks.ndim)
print(np_marks.size)

(3,)
int64
1
3


In [ ]:
data=[10,20,30,40,50,60]
np_data=np.array(data)


In [4]:
test=np.zeros([4,3])
print(test)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
test1=np.ones([4,3])
print(test1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
test2=test1*5
print(test2)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [8]:
test3=test1+test2
print(test3)

[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


In [11]:
data=np.arange(0,10,2)
print(data)

[0 2 4 6 8]


In [13]:
data2=np.linspace(0,10,5)
print(data2)

[ 0.   2.5  5.   7.5 10. ]


In [15]:
data4=np.random.rand(5)
print(np.floor(data4*100))

[69. 27. 12. 54. 21.]


In [16]:
data5=np.random.randint(0,100,10)
print(data5)

[10 82 89 53 43 53 75 59 90 27]


In [18]:
data=np.array([10,20,30,40,50,60])
data2=data.reshape(2,3)
print(data2)

[[10 20 30]
 [40 50 60]]


In [20]:
data7=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(data7)
second_column=data7[:,1]
print(second_column)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 5 8]


In [21]:
avg=np.mean(data7,axis=0)
print(avg)

[4. 5. 6.]


In [22]:
data7[:,[1,2]]=data7[:,[2,1]]
print(data7)

[[1 3 2]
 [4 6 5]
 [7 9 8]]
